# Generated by Django 4.2.2 on 2023-10-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medplus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ('name',), 'verbose_name': 'medicine', 'verbose_name_plural': 'medicines'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
