# Generated by Django 4.2.2 on 2023-11-05 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medplus', '0005_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medplus.medicine')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medplus.cartitem')),
            ],
        ),
    ]
